name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-main-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout MAIN branch
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Build and test
      run: |
        mkdir build
        cd build
        cmake ..
        make
        make test
