name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make 
      run: mkdir build && cd build && cmake ..  -G "Unix Makefiles" && make
    - name: make test
      run: cd build && make && ctest --timeout 900
      
